name: build
run-name: ${{ github.actor }}
on: [push]
jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd backend
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: npm install

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd frontend
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: npm build

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - run: cd frontend
      - run: npm test
