name: ci-frontend
run-name: ${{ github.actor }} pushed changes to Frontend
on: 
  push:
    paths:
      - 'frontend'

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/my-app
    steps:
      - uses: actions/checkout@v3
      - run: yarn --frozen-lockfile
      - run: yarn run lint

  build-frontend:
    needs: lint-frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        # Frontend
        working-directory: frontend/my-app
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: yarn --frozen-lockfile
      - run: yarn build --if--present
      - run: yarn test
  
  docker-frontend:
    needs: build-frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        # Backend
        working-directory: frontend/my-app
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag frontend

